project_id = "uvqugawzhtcajucqbvro"

[functions.process-anomalies]
verify_jwt = false

[functions.analytics-social-media]
verify_jwt = false

[functions.coupons-social-media]
verify_jwt = false

[functions.get-social-media-sales]
verify_jwt = false

[functions.get-attendant-sales-analytics]
verify_jwt = false

[functions.get-subchannel-analytics]
verify_jwt = false