// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvqugawzhtcajucqbvro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cXVnYXd6aHRjYWp1Y3FidnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDMwMzEsImV4cCI6MjA2ODk3OTAzMX0.E38auJWlHy2EtgYgpFaK1b0oOeozr_xFeE-Lp8CY9RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});